name: Deploy to uat

# Controls when the action will run.
on:
  # Triggers the workflow on push to uat branch
  push:
    branches:
      - uat

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run-tests:
        description: "Run Apex tests"
        type: boolean
        default: true
        required: true

jobs:
  deploy:
    uses: wtaxco/wtax-github-actions-workflows/.github/workflows/deploy-sfdx-project-to-uat.yml@main
    with:
      run-tests: ${{ inputs.run-tests == null || inputs.run-tests }}
    secrets:
      ansible-vault-password: ${{ secrets.VAULT_PASSWORD }}
