name: Deploy to prod

# Controls when the action will run.
on:
  # Triggers the workflow on push to master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    uses: wtaxco/wtax-github-actions-workflows/.github/workflows/deploy-sfdx-project-to-prod.yml@main
    secrets:
      ansible-vault-password: ${{ secrets.VAULT_PASSWORD }}
